inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true
Rails/NotNullColumn:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false